project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Arya Zandvakili"

  page-footer:
    left: "&copy; Copyright 2024, Arya Zandvakili"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Research"
        href: research/research.qmd

      - text: "Publications"
        href: publications/publications.qmd

      - text: "Advocacy"
        href: advocacy/advocacy.qmd
        
      - text: "Blog"
        href: blog/blog.qmd
        
      - text: "CV"
        href: cv/cv.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


